baseURL = "http://localhost"
languageCode = "en-us"
title = "Bowen Memorial Methodist Church"
theme = "bowen-theme"

[params]
  description = "Bowen Memorial Methodist Church - Building Faith, Fostering Community, Inspiring Lives"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Welcome"
    url = "/welcome/"
    weight = 2

  [[menu.main]]
    name = "Giving"
    url = "/giving/"
    weight = 3

  [[menu.main]]
    name = "Ministries"
    url = "/ministries/"
    weight = 4

  [[menu.main]]
    name = "Volunteer"
    url = "/volunteer/"
    weight = 5

  [[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 6